#' Viswanathan--Zhou Bootstrap Method
#'
#' Non-parametric bootstrap forecasting method for intermittent demand proposed
#' by Zhou & Viswanathan (2011). The time series is decomposed into demand
#' sizes and inter-demand intervals via Croston's decomposition. Forecasts are
#' generated by independently resampling from the empirical distributions of
#' both components, preserving the marginal structure of the original series.
#'
#' @param formula Model specification.
#' @param object A fitted model object.
#' @param ... Not used.
#'
#' @references
#' Zhou, Chenxi, Viswanathan, S.,  (2011). Comparison of a new bootstrapping method
#' with parametric approaches for safety stock determination in service parts
#' inventory systems.
#' *International Journal of Production Economics* 133(1) 481--485.
#' \doi{10.1016/j.ijpe.2010.09.021}
#'
#'
#' @return A model specification.
#'
#' @examples
#' ts <- tsibble::tsibble(
#'   time = as.Date("2026-01-01") + seq_len(40),
#'   value = rnbinom(40, size = 1, prob = 0.3),
#'   index = time
#' )
#'
#' fc_ts <- ts |>
#'   model(VZ(value)) |>
#'   forecast(h = "7 days")
#'
#' fc_ts |> print()
#'
#'
#' if (requireNamespace("ggtime", quietly = TRUE)) {
#'   library(ggtime)
#'   fc_ts |> autoplot(ts)
#' }
#' @importFrom fabletools new_model_class new_specials new_model_definition
#' @importFrom tsibble measured_vars
#' @importFrom rlang abort is_integerish
#' @importFrom distributional dist_sample
#' @export
VZ <- function(formula, ...) {
  vz_model <- new_model_class(
    "VZ",
    train = train_vz,
    specials = new_specials(
      xreg = vz_no_xreg
    )
  )
  new_model_definition(vz_model, {{ formula }}, ...)
}

train_vz <- function(.data, specials, ...) {
  if (length(measured_vars(.data)) > 1) {
    abort("Only univariate responses are supported by VZ.")
  }

  y <- unclass(.data)[[measured_vars(.data)]]

  if (all(is.na(y))) {
    abort("All observations are missing, a model cannot be estimated without data.")
  }
  if (anyNA(y)) {
    abort("Missing values are not supported by VZ.")
  }
  if (all(y == 0)) {
    abort("The time series is all zero.")
  }

  # Apply Croston's decomposition
  decomp <- crostons_decomp(y)
  demand <- decomp$demand
  intervals <- decomp$intervals

  # Compute fitted values updating the mean demand size and inter-demand irtervals
  rates <- demand / intervals
  expected <- c(NA, cumsum(rates) / seq_along(rates))
  rep_times <- c(intervals, length(y) - sum(intervals))
  fitted <- rep(expected, times = rep_times)
  residuals <- y - fitted

  structure(
    list(
      demand = demand,
      intervals = intervals,
      fitted = fitted,
      residuals = residuals
    ),
    class = "VZ"
  )
}

#' Forecast a VZ model
#'
#' Produces forecast distributions from a fitted VZ model using simulation.
#'
#' @inheritParams forecast.EMPDISTR
#' @param times The number of sample paths to use in estimating the forecast
#'   distribution.
#'
#' @return A distribution vector of forecasts of class `dist_sample`.
#'
#' @examples
#' ts <- tsibble::tsibble(
#'   time = as.Date("2026-01-01") + seq_len(40),
#'   value = rnbinom(40, size = 1, prob = 0.3),
#'   index = time
#' )
#' fit <- model(ts, VZ(value))
#' forecast(fit, h = "7 days")
#'
#' @export
forecast.VZ <- function(object, new_data, specials = NULL, times = 10000, ...) {
  h <- nrow(new_data)
  if (!is_integerish(times) || times <= 0) {
    abort("`times` must be a positive integer.")
  }
  sim <- vz_simulate(object, h, times)
  samples <- as.list(as.data.frame(sim))
  dist_sample(samples)
}

#' Generate sample paths from a VZ model
#'
#' @param x A fitted `VZ` model object.
#' @inheritParams forecast.VZ
#'
#' @return A vector of future paths from a dataset using a fitted model.
#'
#' @examples
#' ts <- tsibble::tsibble(
#'   time = as.Date("2026-01-01") + seq_len(40),
#'   value = rnbinom(40, size = 1, prob = 0.3),
#'   index = time
#' )
#' fit <- model(ts, VZ(value))
#' generate(fit, new_data = tsibble::new_data(ts, 7))
#' @export
generate.VZ <- function(x, new_data, specials = NULL, ...) {
  h <- nrow(new_data)
  sim <- vz_simulate(x, h, 1L)
  new_data$.sim <- as.numeric(sim[1, ])
  new_data
}

#' Extract fitted values from a VZ model
#'
#' @inherit fitted.EMPDISTR
#'
#' @examples
#' ts <- tsibble::tsibble(
#'   time = as.Date("2026-01-01") + seq_len(40),
#'   value = rnbinom(40, size = 1, prob = 0.3),
#'   index = time
#' )
#' fit <- model(ts, VZ(value))
#' fitted(fit)
#' @export
fitted.VZ <- function(object, ...) {
  object$fitted
}

#' Extract residuals from a VZ model
#'
#' @inherit residuals.EMPDISTR
#'
#' @examples
#' ts <- tsibble::tsibble(
#'   time = as.Date("2026-01-01") + seq_len(40),
#'   value = rnbinom(40, size = 1, prob = 0.3),
#'   index = time
#' )
#' fit <- model(ts, VZ(value))
#' residuals(fit)
#' @export
residuals.VZ <- function(object, ...) {
  object$residuals
}


#' @export
model_sum.VZ <- function(x) {
  "VZ"
}

#' @export
tidy.VZ <- function(x, ...) {
  tibble(
    term     = c("mean_demand", "mean_interval"),
    estimate = c(mean(x$demand), mean(x$intervals))
  )
}

#' @rdname VZ
#' @export
report.VZ <- function(object, ...) {
  cat(sprintf("  Demand occurrences:         %d\n", length(object$demand)))
  cat(sprintf("  Mean demand size:           %g\n", mean(object$demand)))
  cat(sprintf("  Mean inter-demand interval: %g\n", mean(object$intervals)))
  invisible(object)
}

vz_simulate <- function(object, h, times) {
  to_sample <- seq_len(times)
  current_time <- rep(0L, times)
  forecast_samples <- matrix(0, nrow = times, ncol = h)

  # Sample demand intervals until exceeding the forecast horizon
  while (length(to_sample) > 0) {
    new_intervals <- sample(object$intervals, length(to_sample), replace = TRUE)
    current_time <- current_time + new_intervals

    # Track the samples that are still within the forecast horizon
    to_replace <- current_time <= h
    current_time <- current_time[to_replace]
    to_sample <- to_sample[to_replace]

    # Mark the sampled demand sizes at the appropriate forecast time steps
    for (i in seq_along(to_sample)) {
      forecast_samples[to_sample[i], current_time[i]] <- 1
    }
  }

  # Replace positive demand via sampling
  to_sample <- forecast_samples > 0
  if (any(to_sample)) {
    forecast_samples[to_sample] <- sample(object$demand, sum(to_sample), replace = TRUE)
  }

  forecast_samples
}

vz_no_xreg <- function(...) {
  abort("Exogenous regressors are not supported by VZ.")
}
